### ISSUE TITLE
Setup Docker for Reconcile Service

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-reconcile#13]
Dockerfile and docker-compose.yml already exists.
Please check if that is ok or changes need to be made.

**Comment by Phu2** [comment]
The `ES_PORT` is declared twice in `.sample.env` and the port to bes exposed to the host is hard coded in `docker-compose.yml`. I'd suggest to use a dedicated variable `ES_PORT_EXPOSED`. See https://github.com/skohub-io/skohub-reconcile/commit/7dc565b8891eade3026eceb58fdd207be361368c

**Comment by Phu2** [comment]
Same for the proposed `KIBANA_PORT_EXPOSED`. See https://github.com/skohub-io/skohub-reconcile/commit/be09cf8ff0b38ec184fc4689bf91d7ca9e02a498
