### ISSUE TITLE
In query responses, change `result` key to `results`

### ISSUE THREAD

**Issue by awagner-mainz** [skohub-io/skohub-reconcile#26]
In the [draft spec (0.3.0-alpha)](https://reconciliation-api.github.io/specs/draft/#dfn-reconciliation-result-batch), the results are in `candidates` arrays that are themselves in a `results` array. To be honest, I find it very confusing, but at least I am sure that the `results` key is _in plural form_, not in the singular form "result".

**Comment by sroertgen** [comment]
you are right. I implemented now a check against the result scheme as well and adapted the response accordingly.

**Comment by acka47** [comment]
Can this be closed then?
